SFT-259 Create And Animate Road Component
UCSolarCarTeam/Helios-Dashboard pull request #3
Opened 2021-07-03 17:35 UTC by Ahmed-I-Abdullah

2021-07-03 19:34 UTC, disneyonbryce requested changes

2021-07-03 19:34 UTC, disneyonbryce commented on src/Road.qml
> +            let baseNum = 0;
@Hesham-E @DatLam25 So what baseNum is, is that it's the starting position of the lines in the middle of the road. I don't think baseNum is a good name for this variable, and I propose _position_ as a better name. However, if any of yall have better names, give em'. @Ahmed-I-Abdullah as well

2021-07-03 19:34 UTC, disneyonbryce commented on src/Road.qml
> +            startAnimation();
Is there a way we can make this non-recursive? I'm just fearing for memory issues later on.

2021-07-03 19:34 UTC, disneyonbryce commented on src/Road.qml
> +            const startAnimation = () => {
Let's create an issue/task on Jira about making startAnimation shorter because I feel that there are too many lines in this. However, this requires more research into _context_ so that's why we should focus on more pressing matters later.

2021-07-03 19:34 UTC, disneyonbryce commented on src/Road.qml
> +            const startAnimation = () => {
@Ahmed-I-Abdullah Maybe add comments across the entire method just explaining it high-level? I think this would be very beneficial to future coders.

2021-07-03 19:34 UTC, disneyonbryce commented on src/Road.qml
> +    property bool animationOn: true
property declarations should be above object properties
https://doc.qt.io/qt-5/qml-codingconventions.html

2021-07-03 19:34 UTC, disneyonbryce commented on src/Road.qml
> +            const startAnimation = () => {
Also remove this outside of _roadCanvas_, and just make it like 
![image](https://user-images.githubusercontent.com/65361192/124365134-4379cb00-dc03-11eb-87b1-9547c0c025e1.png)
where the function is outside of the component

2021-07-03 20:07 UTC, Ahmed-I-Abdullah commented on src/Road.qml
> +            startAnimation();
I think we need to keep calling the method before each repaint for the animation to work, but we can stop the animation or find another way to do it after trying it out with the raspberry pi

2021-07-03 20:09 UTC, Ahmed-I-Abdullah commented on src/Road.qml
> +            let baseNum = 0;
Great suggestion! I changed it to startPosition, lmk if you guys have any other suggestions.

2021-07-09 02:24 UTC, Hesham-E commented
I really like this. Awesome job Ahmed. I only have one comment to add to the conversation. Would it be possible to reduce the road animation speed? Perhaps down to 1.25? I feel that it might be distracting at its current speed.

2021-07-10 20:48 UTC, disneyonbryce commented on src/main.qml
>          }
Minor thing, add a space between gradient property and the Road component

2021-07-10 21:10 UTC, disneyonbryce approved these changes
Okay, so everything is nice.

1) I left a new comment about my last review of startAnimation. What I wrote that my suggestion is not possible so please ignore what I said.

 2) Make sure to comment your startAnimation method
 
 3) Add a space between line 18 and 19 in src/main.qml

2021-07-10 21:11 UTC, disneyonbryce commented on src/Road.qml
> +            const startAnimation = () => {
My above comment is incorrect. It is not possible to remove the function outside of roadCanvas.

2021-07-16 01:52 UTC, DatLam25 approved these changes
Very well done!

2021-07-24 17:48 UTC, merged