Created Signal Bar component
UCSolarCarTeam/Helios-Dashboard pull request #4
Opened 2021-07-10 20:38 UTC by disneyonbryce

2021-07-10 20:40 UTC, disneyonbryce commented on src/SignalBar.qml
> +    //Consider enums/constants for properties?
Asked in Discord - 2021-07-10

2021-07-16 01:49 UTC, DatLam25 commented
I'm getting errors when I'm running the project. 
![Screenshot from 2021-07-15 19-47-21](https://user-images.githubusercontent.com/33644068/125879288-fb740dcc-b39b-4989-a239-c7383a4f9009.png)

2021-07-16 01:51 UTC, DatLam25 commented
For some reason, your SignalBar.qml isn't included in the qml.qrc either.

2021-08-06 01:11 UTC, JessieG123 requested changes
Remember to merge master in to include travis.yml before merging!

2021-08-07 17:31 UTC, JessieG123 approved these changes
Checked the git commit history and I think it should be ok.  LGTM on this the git things :D 

Make sure to rebase your commits into one commit with the commit message following the format I mentioned on discord when you're ready to merge. 

```
SFT-### Title

Description of changes
```

2021-08-07 19:28 UTC, closed without merging