SFT-246 Create Hexagon Component
UCSolarCarTeam/Helios-Dashboard pull request #9
Opened 2021-08-13 01:32 UTC by Hesham-E

Created hexagon component and it's corresponding values. Switched 'Max Temp' label and value to center for aesthetic purposes. Will address rounded corners in another commit.

2021-09-10 02:04 UTC, DatLam25 requested changes
Can you change the size of the number so it is easier to read, currently the numbers is a little small compare everything else.

2021-09-10 02:26 UTC, Hesham-E commented
Sounds good, I'll amend the project.

2021-10-02 17:24 UTC, DatLam25 approved these changes

2021-10-02 17:45 UTC, Ahmed-I-Abdullah commented
It still looks like this on my laptop but if it's just me I guess it's fine
![Capture](https://user-images.githubusercontent.com/70468508/135726912-f35a3b36-113c-416a-9023-64e8bd46451f.PNG)

2021-10-30 19:16 UTC, DatLam25 approved these changes

2021-10-30 19:19 UTC, merged